"""add campaign tables and oauth tokens

Revision ID: e7dc9d6ea445
Revises: 001
Create Date: 2026-02-12 16:00:16.602194

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7dc9d6ea445"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign_leads",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("campaign_id", sa.String(), nullable=False),
        sa.Column("variant_id", sa.String(), nullable=False),
        sa.Column("lead_source", sa.String(), nullable=False),
        sa.Column("fingerprint", sa.String(), nullable=True),
        sa.Column("attributed_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("campaign_leads", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_campaign_leads_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_campaign_leads_variant_id"), ["variant_id"], unique=False
        )

    op.create_table(
        "campaign_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("campaign_id", sa.String(), nullable=False),
        sa.Column("variant_id", sa.String(), nullable=False),
        sa.Column("polled_at", sa.Float(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("likes", sa.Integer(), nullable=False),
        sa.Column("comments", sa.Integer(), nullable=False),
        sa.Column("shares", sa.Integer(), nullable=False),
        sa.Column("engagement", sa.Float(), nullable=False),
        sa.Column("unique_impressions", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("campaign_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_campaign_metrics_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_campaign_metrics_variant_id"), ["variant_id"], unique=False
        )

    op.create_table(
        "campaign_variants",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("campaign_id", sa.String(), nullable=False),
        sa.Column("sentiment", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("linkedin_post_urn", sa.String(), nullable=True),
        sa.Column("published_at", sa.Float(), nullable=True),
        sa.Column("is_selected", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("campaign_variants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_campaign_variants_campaign_id"),
            ["campaign_id"],
            unique=False,
        )

    op.create_table(
        "campaigns",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("organization_urn", sa.String(), nullable=False),
        sa.Column("base_message", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("scheduled_at", sa.Float(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_campaigns_organization_urn"),
            ["organization_urn"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_campaigns_status"), ["status"], unique=False
        )

    op.create_table(
        "linkedin_oauth_tokens",
        sa.Column("organization_urn", sa.String(), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("organization_urn"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("linkedin_oauth_tokens")
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaigns_status"))
        batch_op.drop_index(batch_op.f("ix_campaigns_organization_urn"))

    op.drop_table("campaigns")
    with op.batch_alter_table("campaign_variants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaign_variants_campaign_id"))

    op.drop_table("campaign_variants")
    with op.batch_alter_table("campaign_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaign_metrics_variant_id"))
        batch_op.drop_index(batch_op.f("ix_campaign_metrics_campaign_id"))

    op.drop_table("campaign_metrics")
    with op.batch_alter_table("campaign_leads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaign_leads_variant_id"))
        batch_op.drop_index(batch_op.f("ix_campaign_leads_campaign_id"))

    op.drop_table("campaign_leads")
    # ### end Alembic commands ###
